### ISSUE TITLE
Docs: UserToolbarComponent

### ISSUE THREAD

**Issue by Markus-MfN** [giantmonkey/gomus-components-doc#11]
Related page: [UserToolbarComponent](https://giantmonkey.github.io/gomus-components-doc/components/UserToolbarComponent)

I have separate pages for Login and Registration. How can I configure different URLs for the login and the register button?

**Comment by douglasward** [comment]
The easiest way is to define a custom template.
```html
<go-user-toolbar options='{"action": {"mode": "none"}}'>
    <ng-template>
      <a href="#" go-user-toolbar-login>Anmelden</a>
      <a href="#" go-user-toolbar-register>Registrieren</a>
      <a href="#" go-user-toolbar-profile>Mein Profil</a>
      <button go-user-toolbar-logout>Abmelden</button>
    </ng-template>
  </go-user-toolbar>
```

If you need us to extend the `actions` configuration to support this then please let us know.

**Comment by Markus-MfN** [comment]
Thank you, this should do for now. But I think it would be more consistent to have this in the `actions` configuration.

**Comment by douglasward** [comment]
@maxseeger please take this into account for our backlog.
