### ISSUE TITLE
Docs: CartButtonComponent

### ISSUE THREAD

**Issue by Markus-MfN** [giantmonkey/gomus-components-doc#2]
Related page: [CartButtonComponent](https://giantmonkey.github.io/gomus-components-doc/components/CartButtonComponent)

CartButtonComponent shows "Invalid date".

**Comment by douglasward** [comment]
Hi Markus, I cannot reproduce this. Can you provide some more information?

- html markup
- `_gomusOptions`

**Comment by Markus-MfN** [comment]
Hi Douglas, go to the demo of CartButtonComponent and put a ticket into the cart. Then go to 
cart:

![cartbuttoncomponent](https://user-images.githubusercontent.com/34379007/36737373-2d61589c-1bdb-11e8-800a-24fb050cfcbe.PNG)

**Comment by douglasward** [comment]
Okay, you mean the CartComponent then. The CartButtonComponent you can find on the top right of that page, in the toolbar.

I still can't reproduce this however, although I did find and fix a bug in the date we use to create this formatted date string which could solve the problem. Could you check to see if this is the case?

If not, could you provide your browser and OS version please?

**Comment by Markus-MfN** [comment]
Thank you, Douglas. You've fixed it. Now the date is showing in your demo and on my test page. Tested on Firefox/Ubuntu 16.04 and Chrome/Windows 7.
