### ISSUE TITLE
Docs: CartComponent

### ISSUE THREAD

**Issue by Markus-MfN** [giantmonkey/gomus-components-doc#3]
Related page: [CartComponent](https://giantmonkey.github.io/gomus-components-doc/components/CartComponent)

I'm not familiar with Angular Templates. I would like to show the cart beneath the TicketComponent on the same page. How would a template for the CartComponent look like where the cart is only displayed if it is not empty? And how can I display a message like "your cart is empty" if the cart is empty and dislplay the cart if it is not? Thank you.

**Comment by douglasward** [comment]
Hi Markus, currently this it is not possible to hide the cart when it is empty, as normally it has it's own page. But it sounds as though we could simply solve this with css. 

If I added some helper classes to the `go-cart` element, to indicate whether the cart is empty your contains items, would you be able to use this to hide the cart and display your "empty" message? Or would it be more useful on the `body` element?

**Comment by Markus-MfN** [comment]
Douglas, thanks for your answer. Since what I'm working on is only a test page to show the basic functions, it is not necessary to show the cart is empty message. I was just curious how this would work for future implementation. Our UX experts will decide how it will look like in the end.

**Comment by douglasward** [comment]
Okay, great. Let me know if any extension is needed to be done on our side. Will close this for now.
