### ISSUE TITLE
Docs: UserGuestComponent

### ISSUE THREAD

**Issue by Markus-MfN** [giantmonkey/gomus-components-doc#5]
Related page: [UserGuestComponent](https://giantmonkey.github.io/gomus-components-doc/components/UserGuestComponent),  [UserRegistrationComponent](https://giantmonkey.github.io/gomus-components-doc/components/UserRegistrationComponent)

I've customized the UserGuestComponent to be able to provide a link to our general terms and conditions. I've used the code of Example 2. Now it is possible to order with unchecked box for general terms and conditions. No error appears. Ticket is send via e-mail.

I did the same with the UserRegistrationComponent and with unchecked box for general terms and conditions there is also no error showing, but registration finishes.

**Comment by vollnhals** [comment]
Halo Markus,

looks like the field for "terms and conditions" is sent incorrectly to the backend. We will make a few smaller changes.

**Comment by douglasward** [comment]
Hi Markus, I have updated the example in the [documentation](https://giantmonkey.github.io/gomus-components-doc/components/UserRegistrationComponent.html) to include the correct field name. Should be as follows:
```html
<div go-input-container>
        <label>AGB</label>
        <input type="checkbox" go-form-control="terms" required>
        <span>Ich stimme den allgemeinen Geschäftsbedingungen zu.</span>
        <div go-input-error="terms"></div>
</div>
```

**Comment by Markus-MfN** [comment]
Thanks, Douglas. Used the new code in both cases. Works as expected now.

Error message should read "Müssen akzeptiert werden.", though. Is there a way for me to customize the error message myself? Asking this also in regard of an English version, which will come up sometime.

**Comment by douglasward** [comment]
Very true, thank you for spotting that. The error messages come from go~mus and are currently not customisable. @vollnhals will update the translating within the coming days.

The error messages respect the language set in the `_gomusOptions` object if this answers your question?

**Comment by Markus-MfN** [comment]
Thank you, Douglas. Question answered.
