### ISSUE TITLE
Docs: UserNewPasswordComponent

### ISSUE THREAD

**Issue by Markus-MfN** [giantmonkey/gomus-components-doc#6]
Related page: [UserNewPasswordComponent](https://giantmonkey.github.io/gomus-components-doc/components/UserNewPasswordComponent)

Is this the component for password reset?

I added a page with only this component. I go to the login form and send an "forgot passwort" email. Clicking on the password reset link in the emails takes me to the added page with the UserNewPasswordComponent. I fill in a new passwort and press submit. It says "User not found" ("Benutzer nicht gefunden").

**Comment by douglasward** [comment]
Hi @Markus-MfN, this error message is displayed when the user tries to reset is password when he is not logged in.
After the redirect from the password reset link in the email, the user is automatically logged in so he can then update his password.

Did you change the URL to localhost or something after the redirect? Or did you do something to destroy the user session? 

I tried to reproduce it on your test site to try and help you further, but I can't seem to find the path to your registration/login page.

**Comment by douglasward** [comment]
I have now found the user page and have tested. 

The auth parameters were being added to the wrong place in the URL. I have fixed it for now by adding `#/` to the end of the password reset link in go\~mus. A future go~mus update will fix this properly.

Please close if you can confirm that it is now working as expected.

**Comment by Markus-MfN** [comment]
Still says "Benutzer nicht gefunden". Did you fix it in the staging instance?

**Comment by douglasward** [comment]
Yes, I fixed it in the staging instance. You will need to generate a new password reset link.

**Comment by Markus-MfN** [comment]
I did. Still get the error message.

**Comment by douglasward** [comment]
Looks like you accidentally removed the change in the shop config. I have added it again now.

Please refresh your config page if you are in edit mode before saving again.

**Comment by Markus-MfN** [comment]
Oh, sorry. It's working now, thanks.
