### ISSUE TITLE
Docs: UserPasswordResetComponent

### ISSUE THREAD

**Issue by Markus-MfN** [giantmonkey/gomus-components-doc#7]
Related page: [UserPasswordResetComponent](https://giantmonkey.github.io/gomus-components-doc/components/UserPasswordResetComponent)

Is there a way to show a message to the user saying that an email has been sent and he should click on the link to reset his password?

**Comment by douglasward** [comment]
You can use the `password_reset_url` property in the `actions` object to define a redirect url after a successful form submission. This can be used to display a message to the user.

Please close if this answers your question.

**Comment by Markus-MfN** [comment]
Like this?

`<go-user-login options='{"action": {"mode": "url", "login_url": "<redirect to after login>"}}'>
<go-user-password-reset options='{"action": {"mode": "url", "password_reset_url": "<redirect to after password reset request>"}}'></go-user-password-reset>
</go-user-login>`

Does not work. I'm redirected to `<shop test url>`.

**Comment by douglasward** [comment]
no, there can only be one top level options object. So like this: 
```
 <go-user-login options='{"action": {"mode": "url", "login_url": "<redirect to after login>", "password_reset_url": "<redirect to after password reset request>"}}'></go-user-login>
```

**Comment by Markus-MfN** [comment]
Thanks, working now.
