### ISSUE TITLE
Docs: UserLoginComponent

### ISSUE THREAD

**Issue by Markus-MfN** [giantmonkey/gomus-components-doc#9]
Related page: [UserLoginComponent](https://giantmonkey.github.io/gomus-components-doc/components/UserLoginComponent)

I use the UserLoginComponent on it's own page. I cannot redirect the user after login. I guess it should be

`<go-user-login options='{"action": {"mode": "url", "login_url": "<url to redirect to>"}}'></go-user-login>`

but this and all variations I tried always redirect to `<shop domain>/checkout`.

**Comment by Markus-MfN** [comment]
Miraculously, redirection works now. Anyway, please confirm, that the code above is correct.

**Comment by douglasward** [comment]
Yes, the above code is correct :)
